Move from Travis CI to GitHub Actions
preactjs/preact-router pull request #397
Opened 2021-02-24 12:06 UTC by marvinschopf

Hello!

I ported the Travis CI workflow to GitHub Actions in this pull request.

Travis now no longer offers unrestricted unlimited free builds for open source projects, has become very slow at times and is shutting down their `travis-ci` **_.org_** platform in a few weeks. So unfortunately, in my eyes, it is time to leave Travis CI behind and switch to GitHub Actions.

Kind regards
Marvin

2021-06-02 02:36 UTC, mbrukman commented
@developit, @marvinhagemeister — could you please review this PR?

2021-06-02 02:39 UTC, mbrukman requested changes
@marvinschopf — thanks for making this change! Could you please also update the badge in `README.md` to point to GitHub actions instead of Travis CI?

You can use something like the following (based on what I use in my personal projects):

```md
[![Build Status][github-ci-badge]][github-ci-url]

[github-ci-badge]: https://github.com/preactjs/preact-router/actions/workflows/node.js.yml/badge.svg
[github-ci-url]: https://github.com/preactjs/preact-router/actions/workflows/node.js.yml
```

2021-06-26 05:23 UTC, rschristian submitted a review, later dismissed

2021-06-26 05:23 UTC, rschristian commented on .github/workflows/node.js.yml
> +      - run: npm test
I don't think we need to over-complicate this with a bunch of jobs and Node versions. Let's reduce this down:

```suggestion
name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run test
```

2021-08-31 20:27 UTC, marvinhagemeister approved these changes

2021-08-31 20:27 UTC, merged